title = "barton rhodes"
# logo = "URL to logo"
base_url = "http://localhost:3000"
about = "autopoietic ergodicity and embodied gradualism"
index_site_pages = ["blog"]

[extra]
copyright = "Barton Rhodes"
github = "https://github.com/bmorphism"
twitter = "https://twitter.com/bmorphism"

date_style = "%B %e, %Y"
